# devices.ini

# GGA Lab EGMs
[G920-1]
ip = 172.17.28.65
username = root
password = root1234

[G920-2]
ip = 172.17.28.51
username = root
password = root1234

[G920-3]
ip = 172.17.28.61
username = root
password = root1234

[Quixant-1]
ip = 172.17.28.70
username = root
password = root1234

[Quixant-2]
ip = 172.17.28.91
username = root
password = root1234

# GGA Lab Testracks 
[Testrack-1]
ip = 172.17.28.76
username = root
password = root1234

[Testrack-2]
ip = 172.17.28.77
username = root
password = root1234

[Testrack-3]
ip = 172.17.28.80
username = root
password = root1234

[Testrack-4]
ip = 172.17.28.84
username = root
password = root1234

[Testrack-5]
ip = 172.17.28.85
username = root
password = root1234

# GGA Office
[Quixant-JL]
ip = 172.17.28.89
username = root
password = root1234

[Quixant-Thomas]
ip = 172.17.28.56
username = root
password = root1234